
REM CODEGEN CATEGORY_SEQ

   CREATE SEQUENCE  "CODEGEN"."CATEGORY_SEQ"  MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 
REM CODEGEN CITY_SEQ

   CREATE SEQUENCE  "CODEGEN"."CITY_SEQ"  MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
 
REM CODEGEN CLASSROOM_SEQ

   CREATE SEQUENCE  "CODEGEN"."CLASSROOM_SEQ"  MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 
REM CODEGEN CLASS_ID_SEQ

   CREATE SEQUENCE  "CODEGEN"."CLASS_ID_SEQ"  MINVALUE 1000 MAXVALUE 9999 INCREMENT BY 1 START WITH 1020 CACHE 20 NOORDER  NOCYCLE ;
 
REM CODEGEN CLINICSCHEDULE_SEQ

   CREATE SEQUENCE  "CODEGEN"."CLINICSCHEDULE_SEQ"  MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
 
REM CODEGEN COUNTRY_SEQ

   CREATE SEQUENCE  "CODEGEN"."COUNTRY_SEQ"  MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
 
REM CODEGEN COURSE_SEQ

   CREATE SEQUENCE  "CODEGEN"."COURSE_SEQ"  MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 
REM CODEGEN ELECSUBSCRIPTION_SEQ

   CREATE SEQUENCE  "CODEGEN"."ELECSUBSCRIPTION_SEQ"  MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
 
REM CODEGEN FACILITY_SEQ

   CREATE SEQUENCE  "CODEGEN"."FACILITY_SEQ"  MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 
REM CODEGEN FUNCTIONGROUP_SEQ

   CREATE SEQUENCE  "CODEGEN"."FUNCTIONGROUP_SEQ"  MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
 
REM CODEGEN FUNCTION_SEQ

   CREATE SEQUENCE  "CODEGEN"."FUNCTION_SEQ"  MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
 
REM CODEGEN HISTRORYLOG_SEQ

   CREATE SEQUENCE  "CODEGEN"."HISTRORYLOG_SEQ"  MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
 
REM CODEGEN MATERIAL_SEQ

   CREATE SEQUENCE  "CODEGEN"."MATERIAL_SEQ"  MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
 
REM CODEGEN MORDER_SEQ

   CREATE SEQUENCE  "CODEGEN"."MORDER_SEQ"  MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
 
REM CODEGEN ORDERMATERIAL_SEQ

   CREATE SEQUENCE  "CODEGEN"."ORDERMATERIAL_SEQ"  MINVALUE 0 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 0 NOCACHE  NOORDER  NOCYCLE ;
 
REM CODEGEN ORDERRESPONSE_SEQ

   CREATE SEQUENCE  "CODEGEN"."ORDERRESPONSE_SEQ"  MINVALUE 0 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 0 NOCACHE  NOORDER  NOCYCLE ;
 
REM CODEGEN PROJECT_ID_SEQ

   CREATE SEQUENCE  "CODEGEN"."PROJECT_ID_SEQ"  MINVALUE 100 MAXVALUE 999 INCREMENT BY 1 START WITH 140 CACHE 20 NOORDER  NOCYCLE ;
 
REM CODEGEN REGION_SEQ

   CREATE SEQUENCE  "CODEGEN"."REGION_SEQ"  MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
 
REM CODEGEN REPORTGROUP_SEQ

   CREATE SEQUENCE  "CODEGEN"."REPORTGROUP_SEQ"  MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
 
REM CODEGEN REPORTS_SEQ

   CREATE SEQUENCE  "CODEGEN"."REPORTS_SEQ"  MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
 
REM CODEGEN SCHEDULE_SEQ

   CREATE SEQUENCE  "CODEGEN"."SCHEDULE_SEQ"  MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
 
REM CODEGEN SECURITYLEVEL_SEQ

   CREATE SEQUENCE  "CODEGEN"."SECURITYLEVEL_SEQ"  MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
 
REM CODEGEN SHIPMENTDETAIL_SEQ

   CREATE SEQUENCE  "CODEGEN"."SHIPMENTDETAIL_SEQ"  MINVALUE 0 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 0 NOCACHE  NOORDER  NOCYCLE ;
 
REM CODEGEN STATE_SEQ

   CREATE SEQUENCE  "CODEGEN"."STATE_SEQ"  MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
 
REM CODEGEN SUBCATEGORY_SEQ

   CREATE SEQUENCE  "CODEGEN"."SUBCATEGORY_SEQ"  MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 
REM CODEGEN SUBSCRIPTIONBRAND_SEQ

   CREATE SEQUENCE  "CODEGEN"."SUBSCRIPTIONBRAND_SEQ"  MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 
REM CODEGEN TRAININGPLAN_SEQ

   CREATE SEQUENCE  "CODEGEN"."TRAININGPLAN_SEQ"  MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 ORDER  NOCYCLE ;
 
REM CODEGEN USECASE_ID_SEQ

   CREATE SEQUENCE  "CODEGEN"."USECASE_ID_SEQ"  MINVALUE 1000 MAXVALUE 9999 INCREMENT BY 1 START WITH 1020 CACHE 20 ORDER  NOCYCLE ;
 
REM CODEGEN USERENROLL_SEQ

   CREATE SEQUENCE  "CODEGEN"."USERENROLL_SEQ"  MINVALUE 1 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
 
REM CODEGEN CATEGORY

  CREATE TABLE "CODEGEN"."CATEGORY" 
   (	"CATID" NUMBER(10,0) NOT NULL ENABLE, 
	"CATNAME" VARCHAR2(40 ), 
	 CONSTRAINT "CATEGORY_PK" PRIMARY KEY ("CATID") ENABLE
   ) ;
 
REM CODEGEN CLASSMASTER

  CREATE TABLE "CODEGEN"."CLASSMASTER" 
   (	"USECASE_ID" VARCHAR2(20 ), 
	"CLASS_ID" VARCHAR2(30 ), 
	"CLASS_NAME" VARCHAR2(30 ), 
	 CONSTRAINT "classmaster_pk" PRIMARY KEY ("USECASE_ID", "CLASS_NAME") ENABLE
   ) ;
 
REM CODEGEN CLASSROOM

  CREATE TABLE "CODEGEN"."CLASSROOM" 
   (	"CLASSROOMID" NUMBER(10,0) NOT NULL ENABLE, 
	"CLASSROOMNAME" VARCHAR2(40 ), 
	"CAPACITY" NUMBER(10,0), 
	"FACKEY" NUMBER(10,0), 
	 CONSTRAINT "CLASSROOM_PK" PRIMARY KEY ("CLASSROOMID") ENABLE, 
	 CONSTRAINT "CLASSROOMFACILITY_FK" FOREIGN KEY ("FACKEY")
	  REFERENCES "CODEGEN"."FACILITY" ("FACKEY") ON DELETE CASCADE ENABLE
   ) ;
 
REM CODEGEN CLINICSCHEDULE

  CREATE TABLE "CODEGEN"."CLINICSCHEDULE" 
   (	"CLINICID" NUMBER(10,0) NOT NULL ENABLE, 
	"SCHEDULEID" NUMBER(10,0), 
	"CONTACTNAME" VARCHAR2(100 ), 
	"CONTACTPHONE" VARCHAR2(30 ), 
	"CONTACTEMAIL" VARCHAR2(200 ), 
	"ADDRESS1" VARCHAR2(200 ), 
	"ADDRESS2" VARCHAR2(200 ), 
	"CITY" VARCHAR2(100 ), 
	"STATE" VARCHAR2(50 ), 
	"ZIP" VARCHAR2(20 ), 
	"COUNTRY" VARCHAR2(100 ), 
	"CONTACTPHONEEXT" VARCHAR2(20 ), 
	 CONSTRAINT "CLINICSCHEDULE_PK" PRIMARY KEY ("CLINICID") ENABLE, 
	 CONSTRAINT "CLINICSCHEDULESCHEDULE_FK" FOREIGN KEY ("SCHEDULEID")
	  REFERENCES "CODEGEN"."SCHEDULE" ("SCHEDULEID") ON DELETE CASCADE ENABLE
   ) ;
 
REM CODEGEN CONSIST

  CREATE TABLE "CODEGEN"."CONSIST" 
   (	"COURSESEQUENCE" NUMBER(10,0), 
	"PLANID" NUMBER(10,0), 
	"COURSEKEY" NUMBER(10,0), 
	 CONSTRAINT "CONSISTCOURSE_FK" FOREIGN KEY ("COURSEKEY")
	  REFERENCES "CODEGEN"."COURSE" ("COURSEKEY") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "CONSISTTRAININGPLAN_FK" FOREIGN KEY ("PLANID")
	  REFERENCES "CODEGEN"."TRAININGPLAN" ("PLANID") ON DELETE CASCADE ENABLE
   ) ;
 
REM CODEGEN COUNTRY

  CREATE TABLE "CODEGEN"."COUNTRY" 
   (	"COUNTRYID" NUMBER(10,0) NOT NULL ENABLE, 
	"COUNTRYNAME" VARCHAR2(200 ), 
	 CONSTRAINT "COUNTRY_PK" PRIMARY KEY ("COUNTRYID") ENABLE
   ) ;
 
REM CODEGEN COURSE

  CREATE TABLE "CODEGEN"."COURSE" 
   (	"COURSEID" VARCHAR2(100 ), 
	"COURSENAME" VARCHAR2(200 ), 
	"COURSEDESCRIPTION" VARCHAR2(1000 ), 
	"LENGTH" NUMBER(10,0), 
	"CATID" NUMBER(10,0), 
	"ACTIVE" VARCHAR2(10 ), 
	"SUBCATID" NUMBER(10,0), 
	"COURSEKEY" NUMBER(10,0) NOT NULL ENABLE, 
	"INTENDEDAUDIENCE" VARCHAR2(100 ), 
	"BASEPRICE" NUMBER(10,4), 
	"DISCOUNTPRICE" NUMBER(10,4), 
	 CONSTRAINT "COURSE_PK" PRIMARY KEY ("COURSEKEY") ENABLE, 
	 CONSTRAINT "COURSECATEGORY_FK" FOREIGN KEY ("CATID")
	  REFERENCES "CODEGEN"."CATEGORY" ("CATID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "COURSESUBCATEGORY_FK" FOREIGN KEY ("SUBCATID")
	  REFERENCES "CODEGEN"."SUBCATEGORY" ("SUBCATID") ON DELETE CASCADE ENABLE
   ) ;
 
REM CODEGEN DAOINFO

  CREATE TABLE "CODEGEN"."DAOINFO" 
   (	"CLASSID" VARCHAR2(30 ), 
	"DAOID" VARCHAR2(30 ), 
	"DAONAME" VARCHAR2(30 )
   ) ;
 
REM CODEGEN DBLIST

  CREATE TABLE "CODEGEN"."DBLIST" 
   (	"PROJECTNAME" VARCHAR2(20 ), 
	"USECASES" VARCHAR2(20 ), 
	"FUNCTIONNAME" VARCHAR2(20 ), 
	"INPUT" VARCHAR2(20 ), 
	"OUTPUT" VARCHAR2(20 ), 
	"DBFUNCTIONNAME" VARCHAR2(20 ), 
	"TABLENAME" VARCHAR2(20 ), 
	"DAONAME" VARCHAR2(20 )
   ) ;
 
REM CODEGEN DBLISTSEC

  CREATE TABLE "CODEGEN"."DBLISTSEC" 
   (	"PROJECTNAME" VARCHAR2(20 ), 
	"USECASES" VARCHAR2(20 ), 
	"FUNCTIONNAME" VARCHAR2(20 ), 
	"INPUT" VARCHAR2(20 ), 
	"OUTPUT" VARCHAR2(20 ), 
	"DBFUNCTIONNAME" VARCHAR2(20 ), 
	"TABLENAME" VARCHAR2(20 ), 
	"DAONAME" VARCHAR2(20 ), 
	"STATUS" VARCHAR2(50 )
   ) ;
 
REM CODEGEN ELECSUBSCRIPTION

  CREATE TABLE "CODEGEN"."ELECSUBSCRIPTION" 
   (	"SUBSCRIPTIONID" NUMBER(10,0) NOT NULL ENABLE, 
	"NAME" VARCHAR2(40 ), 
	"ADDRESS1" VARCHAR2(200 ), 
	"ADDRESS2" VARCHAR2(200 ), 
	"COUNTRY" VARCHAR2(200 ), 
	"STATE" VARCHAR2(50 ), 
	"CITY" VARCHAR2(100 ), 
	"ZIP" VARCHAR2(20 ), 
	"EMAIL" VARCHAR2(200 ), 
	"SUBSCRIBEDDATE" DATE, 
	"BRANDID" NUMBER(10,0), 
	"EXPIRYDATE" DATE, 
	"USERNAME" VARCHAR2(100 ), 
	 CONSTRAINT "ELECSUBSCRIPTION_PK" PRIMARY KEY ("SUBSCRIPTIONID") ENABLE, 
	 CONSTRAINT "ELECSUBSCRIPTIONBRAND_FK" FOREIGN KEY ("BRANDID")
	  REFERENCES "CODEGEN"."SUBSCRIPTIONBRAND" ("BRANDID") ON DELETE CASCADE ENABLE
   ) ;
 
REM CODEGEN FACILITY

  CREATE TABLE "CODEGEN"."FACILITY" 
   (	"FACID" VARCHAR2(100 ), 
	"REGIONID" NUMBER(10,0), 
	"FACNAME" VARCHAR2(200 ), 
	"FACADDRESS1" VARCHAR2(200 ), 
	"STATEID" NUMBER(10,0), 
	"FACZIP" VARCHAR2(30 ), 
	"FACADDRESS2" VARCHAR2(200 ), 
	"DELETED" NUMBER(1,0), 
	"FACPHONE" VARCHAR2(100 ), 
	"FACTYPE" VARCHAR2(20 ), 
	"FACPHONEEXT" VARCHAR2(20 ), 
	"NOOFCLASSROOMS" NUMBER(10,0), 
	"FACKEY" NUMBER(10,0) NOT NULL ENABLE, 
	"FACIMAGE" VARCHAR2(200 ), 
	"FACTOOLSOFINV" VARCHAR2(200 ), 
	"LASTUPDATEDBY" VARCHAR2(200 ), 
	"LASTUPDATETIMESTAMP" DATE, 
	"CITY" VARCHAR2(300 ), 
	 CONSTRAINT "FACILITY_PK" PRIMARY KEY ("FACKEY") ENABLE, 
	 CONSTRAINT "FACILITYREGION_FK" FOREIGN KEY ("REGIONID")
	  REFERENCES "CODEGEN"."REGION" ("REGIONID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "FACILITYSTATE_FK" FOREIGN KEY ("STATEID")
	  REFERENCES "CODEGEN"."STATE" ("STATEID") ON DELETE CASCADE ENABLE
   ) ;
 
REM CODEGEN FINANCIALPWD

  CREATE TABLE "CODEGEN"."FINANCIALPWD" 
   (	"PASSWORD" VARCHAR2(100 )
   ) ;
 
REM CODEGEN FRONTTOPAGE

  CREATE TABLE "CODEGEN"."FRONTTOPAGE" 
   (	"USECASESID" VARCHAR2(30 ), 
	"TOACTION" VARCHAR2(30 )
   ) ;
 
REM CODEGEN FUNCTION

  CREATE TABLE "CODEGEN"."FUNCTION" 
   (	"FUNCTIONID" NUMBER(10,0) NOT NULL ENABLE, 
	"FUNCTIONNAME" VARCHAR2(200 ), 
	"GROUPID" NUMBER(10,0), 
	"LINK" VARCHAR2(400 ), 
	 CONSTRAINT "FUNCTION_PK" PRIMARY KEY ("FUNCTIONID") ENABLE, 
	 CONSTRAINT "FUNCTIONGROUP_FK" FOREIGN KEY ("GROUPID")
	  REFERENCES "CODEGEN"."FUNCTIONGROUP" ("GROUPID") ON DELETE CASCADE ENABLE
   ) ;
 
REM CODEGEN FUNCTIONGROUP

  CREATE TABLE "CODEGEN"."FUNCTIONGROUP" 
   (	"GROUPID" NUMBER(10,0) NOT NULL ENABLE, 
	"GROUPNAME" VARCHAR2(100 ), 
	 CONSTRAINT "FUNCTIONGROUP_PK" PRIMARY KEY ("GROUPID") ENABLE
   ) ;
 
REM CODEGEN INPUTPARADATATYPE

  CREATE TABLE "CODEGEN"."INPUTPARADATATYPE" 
   (	"METHODID" VARCHAR2(30 ), 
	"INPUTPARAMETER" VARCHAR2(30 )
   ) ;
 
REM CODEGEN METHODINFO

  CREATE TABLE "CODEGEN"."METHODINFO" 
   (	"CLASS_ID" VARCHAR2(30 ), 
	"METHOD_ID" VARCHAR2(30 ), 
	"METHOD_NAME" VARCHAR2(30 ), 
	"METHOD_INPUT" VARCHAR2(50 ), 
	"METHOD_OUTPUT" VARCHAR2(50 ), 
	"METHOD_OPERATION" VARCHAR2(50 ), 
	"METHOD_TABLE" VARCHAR2(50 )
   ) ;
 
REM CODEGEN METHODPARAMDETAIL

  CREATE TABLE "CODEGEN"."METHODPARAMDETAIL" 
   (	"METHOD_ID" VARCHAR2(50 ) NOT NULL ENABLE, 
	"METHOD_PARAM_NAME" VARCHAR2(50 ) NOT NULL ENABLE, 
	"METHOD_TABLE_TYPE" VARCHAR2(50 ) NOT NULL ENABLE
   ) ;
 
REM CODEGEN MORDER

  CREATE TABLE "CODEGEN"."MORDER" 
   (	"ORDERID" NUMBER(10,0) NOT NULL ENABLE, 
	"REGIONID" NUMBER(10,0), 
	"STATEID" NUMBER(10,0), 
	"REQUESTP" VARCHAR2(100 ), 
	"APPROVEP" VARCHAR2(100 ), 
	"APPROVED" NUMBER(1,0), 
	"REQUESTTIME" DATE, 
	"COURSEKEY" NUMBER(10,0), 
	"APPROVETIME" DATE, 
	"CATID" NUMBER(10,0), 
	"CLASSROOMID" NUMBER(10,0), 
	"SUBCATID" NUMBER(10,0), 
	"SCHEDULEID" NUMBER(10,0), 
	"CITYID" NUMBER(10,0), 
	"OTHERORDER" NUMBER(1,0), 
	"CLINICID" NUMBER(10,0), 
	"TRACKNUM" VARCHAR2(100 ), 
	"CONTACTP" VARCHAR2(100 ), 
	"ORDERNOTE" VARCHAR2(500 ), 
	"SHIPPED" NUMBER(1,0), 
	"PAID" NUMBER(1,0), 
	"BNAME" VARCHAR2(100 ), 
	"BADDRESS" VARCHAR2(200 ), 
	"BCITY" VARCHAR2(100 ), 
	"BSTATE" VARCHAR2(20 ), 
	"BZIP" VARCHAR2(30 ), 
	"ADDRESS" VARCHAR2(200 ), 
	"CITY" VARCHAR2(100 ), 
	"ZIP" VARCHAR2(30 ), 
	"TOTAL" NUMBER(19,4), 
	"SEND" NUMBER(1,0), 
	"SENDDATE" DATE, 
	"COUNTRY" VARCHAR2(100 ), 
	"BCOUNTRY" VARCHAR2(100 ), 
	"BUSNAME" VARCHAR2(100 ), 
	"ORDERQTY" NUMBER(14,4), 
	"PRICE" NUMBER(14,4), 
	"FACKEY" NUMBER(10,0), 
	"NAME" VARCHAR2(100 ), 
	"BPHONE" VARCHAR2(100 ), 
	"BEMAIL" VARCHAR2(200 ), 
	"ORDERCONFIRMATIONNUMBER" VARCHAR2(100 ), 
	"FULFILLMENTHOUSE" VARCHAR2(300 ), 
	"SHIPSERVICE" VARCHAR2(300 ), 
	"STATE" VARCHAR2(50 ), 
	"BADDRESS2" VARCHAR2(100 ), 
	"ORDERCODE" VARCHAR2(100 ), 
	"DELETED" NUMBER(1,0), 
	 CONSTRAINT "MORDER_PK" PRIMARY KEY ("ORDERID") ENABLE, 
	 CONSTRAINT "MORDERCATEGORY_FK" FOREIGN KEY ("CATID")
	  REFERENCES "CODEGEN"."CATEGORY" ("CATID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "MORDERCOURSE_FK" FOREIGN KEY ("COURSEKEY")
	  REFERENCES "CODEGEN"."COURSE" ("COURSEKEY") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "MORDERSCHEDULE_FK" FOREIGN KEY ("SCHEDULEID")
	  REFERENCES "CODEGEN"."SCHEDULE" ("SCHEDULEID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "MORDERSUBCATEGORY_FK" FOREIGN KEY ("SUBCATID")
	  REFERENCES "CODEGEN"."SUBCATEGORY" ("SUBCATID") ON DELETE CASCADE ENABLE
   ) ;
 
REM CODEGEN MORDERDETAIL

  CREATE TABLE "CODEGEN"."MORDERDETAIL" 
   (	"MATERIALKEY" NUMBER(10,0), 
	"QUANTITY" NUMBER(10,0), 
	"ORDERID" NUMBER(10,0), 
	 CONSTRAINT "MORDERDETAILMORDER_FK" FOREIGN KEY ("ORDERID")
	  REFERENCES "CODEGEN"."MORDER" ("ORDERID") ON DELETE CASCADE ENABLE
   ) ;
 
REM CODEGEN ORDERMATERIAL

  CREATE TABLE "CODEGEN"."ORDERMATERIAL" 
   (	"ORDERMATERIALKEY" NUMBER(10,0) NOT NULL ENABLE, 
	"ORDERRESPONSEKEY" NUMBER(10,0), 
	"ORDERSTATUS" VARCHAR2(50 ), 
	"REASON" VARCHAR2(100 ), 
	"SHIPPINGWEIGHT" NUMBER(14,4), 
	"MATERIALID" VARCHAR2(50 ), 
	 CONSTRAINT "ORDERMATERIAL_PK" PRIMARY KEY ("ORDERMATERIALKEY") ENABLE, 
	 CONSTRAINT "ORDERMATERIALORDERRESP_FK" FOREIGN KEY ("ORDERRESPONSEKEY")
	  REFERENCES "CODEGEN"."ORDERRESPONSE" ("ORDERRESPONSEKEY") ON DELETE CASCADE ENABLE
   ) ;
 
REM CODEGEN ORDERRESPONSE

  CREATE TABLE "CODEGEN"."ORDERRESPONSE" 
   (	"ORDERRESPONSEKEY" NUMBER(10,0) NOT NULL ENABLE, 
	"ORDERRESPONSEID" VARCHAR2(100 ), 
	"DESCRIPTION" VARCHAR2(200 ), 
	"ORDERID" NUMBER(10,0), 
	"ISSUEDATE" DATE, 
	"FULFILLMENTHOUSE" VARCHAR2(50 ), 
	"ORDERCUSTOMER" VARCHAR2(50 ), 
	"NOTES" VARCHAR2(200 ), 
	 CONSTRAINT "ORDERRESPONSE_PK" PRIMARY KEY ("ORDERRESPONSEKEY") ENABLE, 
	 CONSTRAINT "ORDERRESPONSEORDER_FK" FOREIGN KEY ("ORDERID")
	  REFERENCES "CODEGEN"."MORDER" ("ORDERID") ON DELETE CASCADE ENABLE
   ) ;
 
REM CODEGEN PREREQUISITE

  CREATE TABLE "CODEGEN"."PREREQUISITE" 
   (	"COURSEKEY" NUMBER(10,0), 
	"PREREQUISITE" NUMBER(10,0), 
	 CONSTRAINT "PREREQUISITECOURSE_FK" FOREIGN KEY ("COURSEKEY")
	  REFERENCES "CODEGEN"."COURSE" ("COURSEKEY") ON DELETE CASCADE ENABLE
   ) ;
 
REM CODEGEN PROJECTMASTER

  CREATE TABLE "CODEGEN"."PROJECTMASTER" 
   (	"PROJECT_ID" VARCHAR2(50 ) NOT NULL ENABLE, 
	"PROJECT_NAME" VARCHAR2(100 ) NOT NULL ENABLE, 
	 CONSTRAINT "projectmaster_pk" PRIMARY KEY ("PROJECT_NAME") ENABLE
   ) ;
 
REM CODEGEN PWDHISTORY

  CREATE TABLE "CODEGEN"."PWDHISTORY" 
   (	"USERNAME" VARCHAR2(100 ), 
	"PASSWORD" VARCHAR2(100 ) NOT NULL ENABLE, 
	"PWD_MODIFIED_DATE" DATE NOT NULL ENABLE
   ) ;
 
REM CODEGEN REGION

  CREATE TABLE "CODEGEN"."REGION" 
   (	"REGIONID" NUMBER(10,0) NOT NULL ENABLE, 
	"REGIONNAME" VARCHAR2(100 ), 
	"COUNTRYID" NUMBER(10,0), 
	 CONSTRAINT "REGION_PK" PRIMARY KEY ("REGIONID") ENABLE, 
	 CONSTRAINT "REGIONCOUNTRY_FK" FOREIGN KEY ("COUNTRYID")
	  REFERENCES "CODEGEN"."COUNTRY" ("COUNTRYID") ON DELETE CASCADE ENABLE
   ) ;
 
REM CODEGEN REPORTGROUP

  CREATE TABLE "CODEGEN"."REPORTGROUP" 
   (	"GROUPID" NUMBER(10,0) NOT NULL ENABLE, 
	"GROUPNAME" VARCHAR2(100 ), 
	 CONSTRAINT "REPORTGROUP_PK" PRIMARY KEY ("GROUPID") ENABLE
   ) ;
 
REM CODEGEN REPORTS

  CREATE TABLE "CODEGEN"."REPORTS" 
   (	"REPID" NUMBER(10,0) NOT NULL ENABLE, 
	"REPNAME" VARCHAR2(200 ), 
	"GROUPID" NUMBER(10,0), 
	"LINK" VARCHAR2(100 ), 
	 CONSTRAINT "REPORTS_PK" PRIMARY KEY ("REPID") ENABLE, 
	 CONSTRAINT "REPORTSREPORTGROUP_FK" FOREIGN KEY ("GROUPID")
	  REFERENCES "CODEGEN"."REPORTGROUP" ("GROUPID") ON DELETE CASCADE ENABLE
   ) ;
 
REM CODEGEN REPSECLEVEL

  CREATE TABLE "CODEGEN"."REPSECLEVEL" 
   (	"REPID" NUMBER(10,0), 
	"SECLEVELID" NUMBER(10,0), 
	"GROUPID" NUMBER(10,0), 
	 CONSTRAINT "REPSECLEVELREPORTSGROUP_FK" FOREIGN KEY ("GROUPID")
	  REFERENCES "CODEGEN"."REPORTGROUP" ("GROUPID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "REPSECLEVELREPORTS_FK" FOREIGN KEY ("REPID")
	  REFERENCES "CODEGEN"."REPORTS" ("REPID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "REPSECLEVELSECURITYLEVEL_FK" FOREIGN KEY ("SECLEVELID")
	  REFERENCES "CODEGEN"."SECURITYLEVEL" ("SECLEVELID") ON DELETE CASCADE ENABLE
   ) ;
 
REM CODEGEN SCHEDULE

  CREATE TABLE "CODEGEN"."SCHEDULE" 
   (	"SCHEDULEID" NUMBER(10,0) NOT NULL ENABLE, 
	"COURSEKEY" NUMBER(10,0), 
	"STARTDATE" DATE, 
	"CLASSROOMID" NUMBER(10,0), 
	"SUBCATID" NUMBER(10,0), 
	"INSTRUCTORID" VARCHAR2(100 ), 
	"REGIONID" NUMBER(10,0), 
	"NOTE" VARCHAR2(500 ), 
	"COMPLETED" NUMBER(1,0), 
	"SCHEDLENGTH" NUMBER(10,0), 
	"HOLD" NUMBER(1,0), 
	"CATID" NUMBER(10,0), 
	"CANCELED" NUMBER(1,0), 
	"STATUS" VARCHAR2(20 ), 
	"SCHEDULETYPE" VARCHAR2(20 ), 
	"CAPACITY" NUMBER(10,0), 
	"LASTUPDATEDUSERNAME" VARCHAR2(100 ) NOT NULL ENABLE, 
	"LASTUPDATEDDATE" DATE, 
	"MINIMUMGRADE" NUMBER(10,0), 
	"ENDDATE" DATE, 
	"FACKEY" NUMBER(10,0), 
	 CONSTRAINT "SCHEDULE_PK" PRIMARY KEY ("SCHEDULEID") ENABLE, 
	 CONSTRAINT "SCHEDULECATEGORY_FK" FOREIGN KEY ("CATID")
	  REFERENCES "CODEGEN"."CATEGORY" ("CATID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "SCHEDULECLASSROOM_FK" FOREIGN KEY ("CLASSROOMID")
	  REFERENCES "CODEGEN"."CLASSROOM" ("CLASSROOMID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "SCHEDULECOURSE_FK" FOREIGN KEY ("COURSEKEY")
	  REFERENCES "CODEGEN"."COURSE" ("COURSEKEY") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "SCHEDULEFACILITY_FK" FOREIGN KEY ("FACKEY")
	  REFERENCES "CODEGEN"."FACILITY" ("FACKEY") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "SCHEDULEREGION_FK" FOREIGN KEY ("REGIONID")
	  REFERENCES "CODEGEN"."REGION" ("REGIONID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "SCHEDULESUBCATEGORY_FK" FOREIGN KEY ("SUBCATID")
	  REFERENCES "CODEGEN"."SUBCATEGORY" ("SUBCATID") ON DELETE CASCADE ENABLE
   ) ;
 
REM CODEGEN SECURITYLEVEL

  CREATE TABLE "CODEGEN"."SECURITYLEVEL" 
   (	"SECLEVELID" NUMBER(10,0) NOT NULL ENABLE, 
	"SECLEVELNAME" VARCHAR2(200 ), 
	 CONSTRAINT "SECURITYLEVEL_PK" PRIMARY KEY ("SECLEVELID") ENABLE
   ) ;
 
REM CODEGEN SHIPMENTDETAIL

  CREATE TABLE "CODEGEN"."SHIPMENTDETAIL" 
   (	"SHIPMENTKEY" NUMBER(10,0) NOT NULL ENABLE, 
	"SHIPMENTID" VARCHAR2(100 ), 
	"FREIGHTFORWARDERPARTY" VARCHAR2(100 ), 
	"ALTERNATEMATERIALID" VARCHAR2(50 ), 
	"ORDERMATERIALKEY" NUMBER(10,0), 
	 CONSTRAINT "SHIPMENTDETAIL_PK" PRIMARY KEY ("SHIPMENTKEY") ENABLE, 
	 CONSTRAINT "SHIPMENTDETAILORDERMATERIAL_FK" FOREIGN KEY ("ORDERMATERIALKEY")
	  REFERENCES "CODEGEN"."ORDERMATERIAL" ("ORDERMATERIALKEY") ENABLE
   ) ;
 
REM CODEGEN STATE

  CREATE TABLE "CODEGEN"."STATE" 
   (	"STATE" VARCHAR2(100 ), 
	"STATEID" NUMBER(10,0) NOT NULL ENABLE, 
	"ABBRE" VARCHAR2(10 ), 
	"REGIONID" NUMBER(10,0), 
	"COUNTRYID" NUMBER(10,0), 
	 CONSTRAINT "STATE_PK" PRIMARY KEY ("STATEID") ENABLE, 
	 CONSTRAINT "STARTCOUNTRY_FK" FOREIGN KEY ("COUNTRYID")
	  REFERENCES "CODEGEN"."COUNTRY" ("COUNTRYID") ENABLE, 
	 CONSTRAINT "STATEREGION_FK" FOREIGN KEY ("REGIONID")
	  REFERENCES "CODEGEN"."REGION" ("REGIONID") ON DELETE CASCADE ENABLE
   ) ;
 
REM CODEGEN STUDENTSTATUS

  CREATE TABLE "CODEGEN"."STUDENTSTATUS" 
   (	"STATUS" VARCHAR2(5 ), 
	"DESCRIPTION" VARCHAR2(25 )
   ) ;
 
REM CODEGEN SUBCATEGORY

  CREATE TABLE "CODEGEN"."SUBCATEGORY" 
   (	"SUBCATID" NUMBER(10,0) NOT NULL ENABLE, 
	"SUBCATNAME" VARCHAR2(40 ), 
	"CATID" NUMBER(10,0), 
	 CONSTRAINT "SUBCATEGORY_PK" PRIMARY KEY ("SUBCATID") ENABLE, 
	 CONSTRAINT "SUBCATEGORYCATEGORY_FK" FOREIGN KEY ("CATID")
	  REFERENCES "CODEGEN"."CATEGORY" ("CATID") ON DELETE CASCADE ENABLE
   ) ;
 
REM CODEGEN SUBORDER

  CREATE TABLE "CODEGEN"."SUBORDER" 
   (	"ORDERID" NUMBER(10,0), 
	"NAME" VARCHAR2(200 ), 
	"ADDRESS" VARCHAR2(200 ), 
	"CITY" VARCHAR2(200 ), 
	"STATE" VARCHAR2(100 ), 
	"ZIP" VARCHAR2(20 ), 
	"EMAIL" VARCHAR2(300 ), 
	"TELEPHONE" VARCHAR2(40 ), 
	"ORDERTIME" DATE, 
	"TOTAL" FLOAT(53), 
	"DATEID" NUMBER(10,0), 
	"USERID" NUMBER(10,0), 
	"ORDERIP" VARCHAR2(100 )
   ) ;
 
REM CODEGEN SUBSCRIPTIONBRAND

  CREATE TABLE "CODEGEN"."SUBSCRIPTIONBRAND" 
   (	"BRANDID" NUMBER(10,0) NOT NULL ENABLE, 
	"BRANDNAME" VARCHAR2(100 ), 
	"VALIDDAYS" VARCHAR2(20 ), 
	"SUBSCRIPTIONRATES" NUMBER(14,4), 
	 CONSTRAINT "SUBSCRIPTIONBRAND_PK" PRIMARY KEY ("BRANDID") ENABLE
   ) ;
 
REM CODEGEN TIME

  CREATE TABLE "CODEGEN"."TIME" 
   (	"TIME" VARCHAR2(20 )
   ) ;
 
REM CODEGEN TRAININGMATERIAL

  CREATE TABLE "CODEGEN"."TRAININGMATERIAL" 
   (	"COURSEKEY" NUMBER(10,0), 
	"MATERIALKEY" NUMBER(10,0), 
	"CATID" NUMBER(10,0), 
	"SUBCATID" NUMBER(10,0), 
	 CONSTRAINT "TRAININGMATERIALCATEGORY_FK" FOREIGN KEY ("CATID")
	  REFERENCES "CODEGEN"."CATEGORY" ("CATID") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "TRAININGMATERIALCOURSE_FK" FOREIGN KEY ("COURSEKEY")
	  REFERENCES "CODEGEN"."COURSE" ("COURSEKEY") ON DELETE CASCADE ENABLE, 
	 CONSTRAINT "TRAININGMATERIALSUBCATEGORY_FK" FOREIGN KEY ("SUBCATID")
	  REFERENCES "CODEGEN"."SUBCATEGORY" ("SUBCATID") ON DELETE CASCADE ENABLE
   ) ;
 
REM CODEGEN TRAININGPLAN

  CREATE TABLE "CODEGEN"."TRAININGPLAN" 
   (	"PLANID" NUMBER(10,0) NOT NULL ENABLE, 
	"PLANNAME" VARCHAR2(200 ), 
	"NOTE" VARCHAR2(500 ), 
	"ACTIVE" VARCHAR2(10 ), 
	"DELETED" CHAR(1 ), 
	 CONSTRAINT "TRAININGPLAN_PK" PRIMARY KEY ("PLANID") ENABLE
   ) ;
 
REM CODEGEN USECASEMASTER

  CREATE TABLE "CODEGEN"."USECASEMASTER" 
   (	"USECASE_ID" VARCHAR2(50 ), 
	"USECASE_NAME" VARCHAR2(100 ), 
	"PROJECT_ID" VARCHAR2(50 ) NOT NULL ENABLE, 
	 CONSTRAINT "usecasemaster_pk" PRIMARY KEY ("USECASE_NAME", "PROJECT_ID") ENABLE
   ) ;
 
REM CODEGEN USECASESSCREEN

  CREATE TABLE "CODEGEN"."USECASESSCREEN" 
   (	"USEID" VARCHAR2(20 ), 
	"SCREENID" VARCHAR2(20 ), 
	"SCREENNAME" VARCHAR2(20 ), 
	"SUCCESSSCREEN" VARCHAR2(20 ), 
	"FAILURESCREEN" VARCHAR2(20 )
   ) ;
 
REM CODEGEN USERENROLL

  CREATE TABLE "CODEGEN"."USERENROLL" 
   (	"USERNAME" VARCHAR2(100 ), 
	"REGTIME" DATE, 
	"SCHEDULEID" NUMBER(10,0), 
	"DROPTIME" DATE, 
	"DROPPED" NUMBER(1,0), 
	"PAID" NUMBER(1,0), 
	"PRETESTSCORE" NUMBER(10,0), 
	"POSTTESTSCORE" NUMBER(10,0), 
	"STUDENTSTATUS" VARCHAR2(20 ), 
	"REGISTERTYPE" VARCHAR2(50 ), 
	"WAITING" VARCHAR2(50 ), 
	"AMOUNT" NUMBER(10,4), 
	"CERTIFICATESTATUS" CHAR(1 ), 
	"ENROLLMENTID" NUMBER(10,0) NOT NULL ENABLE, 
	 CONSTRAINT "USERENROLL_PK" PRIMARY KEY ("ENROLLMENTID") ENABLE, 
	 CONSTRAINT "USERENROLLSCHEDULE_FK" FOREIGN KEY ("SCHEDULEID")
	  REFERENCES "CODEGEN"."SCHEDULE" ("SCHEDULEID") ON DELETE CASCADE ENABLE
   ) ;
 
REM CODEGEN CATEGORY_PK

  CREATE UNIQUE INDEX "CODEGEN"."CATEGORY_PK" ON "CODEGEN"."CATEGORY" ("CATID") 
  ;
 
REM CODEGEN classmaster_pk

  CREATE UNIQUE INDEX "CODEGEN"."classmaster_pk" ON "CODEGEN"."CLASSMASTER" ("USECASE_ID", "CLASS_NAME") 
  ;
 
REM CODEGEN CLASSROOM_PK

  CREATE UNIQUE INDEX "CODEGEN"."CLASSROOM_PK" ON "CODEGEN"."CLASSROOM" ("CLASSROOMID") 
  ;
 
REM CODEGEN CLINICSCHEDULE_PK

  CREATE UNIQUE INDEX "CODEGEN"."CLINICSCHEDULE_PK" ON "CODEGEN"."CLINICSCHEDULE" ("CLINICID") 
  ;
 
REM CODEGEN SYS_C002877

  CREATE UNIQUE INDEX "CODEGEN"."SYS_C002877" ON "CODEGEN"."CLINICSCHEDULE" ("SCHEDULEID") 
  ;
 
REM CODEGEN COUNTRY_PK

  CREATE UNIQUE INDEX "CODEGEN"."COUNTRY_PK" ON "CODEGEN"."COUNTRY" ("COUNTRYID") 
  ;
 
REM CODEGEN COURSE_PK

  CREATE UNIQUE INDEX "CODEGEN"."COURSE_PK" ON "CODEGEN"."COURSE" ("COURSEKEY") 
  ;
 
REM CODEGEN XPKCOURSE

  CREATE UNIQUE INDEX "CODEGEN"."XPKCOURSE" ON "CODEGEN"."COURSE" ("CATID", "SUBCATID", "COURSEKEY") 
  ;
 
REM CODEGEN ELECSUBSCRIPTION_PK

  CREATE UNIQUE INDEX "CODEGEN"."ELECSUBSCRIPTION_PK" ON "CODEGEN"."ELECSUBSCRIPTION" ("SUBSCRIPTIONID") 
  ;
 
REM CODEGEN FACILITY_PK

  CREATE UNIQUE INDEX "CODEGEN"."FACILITY_PK" ON "CODEGEN"."FACILITY" ("FACKEY") 
  ;
 
REM CODEGEN FUNCTION_PK

  CREATE UNIQUE INDEX "CODEGEN"."FUNCTION_PK" ON "CODEGEN"."FUNCTION" ("FUNCTIONID") 
  ;
 
REM CODEGEN FUNCTIONGROUP_PK

  CREATE UNIQUE INDEX "CODEGEN"."FUNCTIONGROUP_PK" ON "CODEGEN"."FUNCTIONGROUP" ("GROUPID") 
  ;
 
REM CODEGEN MORDER_PK

  CREATE UNIQUE INDEX "CODEGEN"."MORDER_PK" ON "CODEGEN"."MORDER" ("ORDERID") 
  ;
 
REM CODEGEN ORDERMATERIAL_PK

  CREATE UNIQUE INDEX "CODEGEN"."ORDERMATERIAL_PK" ON "CODEGEN"."ORDERMATERIAL" ("ORDERMATERIALKEY") 
  ;
 
REM CODEGEN ORDERRESPONSE_PK

  CREATE UNIQUE INDEX "CODEGEN"."ORDERRESPONSE_PK" ON "CODEGEN"."ORDERRESPONSE" ("ORDERRESPONSEKEY") 
  ;
 
REM CODEGEN projectmaster_pk

  CREATE UNIQUE INDEX "CODEGEN"."projectmaster_pk" ON "CODEGEN"."PROJECTMASTER" ("PROJECT_NAME") 
  ;
 
REM CODEGEN REGION_PK

  CREATE UNIQUE INDEX "CODEGEN"."REGION_PK" ON "CODEGEN"."REGION" ("REGIONID") 
  ;
 
REM CODEGEN REPORTGROUP_PK

  CREATE UNIQUE INDEX "CODEGEN"."REPORTGROUP_PK" ON "CODEGEN"."REPORTGROUP" ("GROUPID") 
  ;
 
REM CODEGEN REPORTS_PK

  CREATE UNIQUE INDEX "CODEGEN"."REPORTS_PK" ON "CODEGEN"."REPORTS" ("REPID") 
  ;
 
REM CODEGEN SCHEDULE_PK

  CREATE UNIQUE INDEX "CODEGEN"."SCHEDULE_PK" ON "CODEGEN"."SCHEDULE" ("SCHEDULEID") 
  ;
 
REM CODEGEN SECURITYLEVEL_PK

  CREATE UNIQUE INDEX "CODEGEN"."SECURITYLEVEL_PK" ON "CODEGEN"."SECURITYLEVEL" ("SECLEVELID") 
  ;
 
REM CODEGEN SHIPMENTDETAIL_PK

  CREATE UNIQUE INDEX "CODEGEN"."SHIPMENTDETAIL_PK" ON "CODEGEN"."SHIPMENTDETAIL" ("SHIPMENTKEY") 
  ;
 
REM CODEGEN STATE_PK

  CREATE UNIQUE INDEX "CODEGEN"."STATE_PK" ON "CODEGEN"."STATE" ("STATEID") 
  ;
 
REM CODEGEN SUBCATEGORY_PK

  CREATE UNIQUE INDEX "CODEGEN"."SUBCATEGORY_PK" ON "CODEGEN"."SUBCATEGORY" ("SUBCATID") 
  ;
 
REM CODEGEN SUBSCRIPTIONBRAND_PK

  CREATE UNIQUE INDEX "CODEGEN"."SUBSCRIPTIONBRAND_PK" ON "CODEGEN"."SUBSCRIPTIONBRAND" ("BRANDID") 
  ;
 
REM CODEGEN TRAININGPLAN_PK

  CREATE UNIQUE INDEX "CODEGEN"."TRAININGPLAN_PK" ON "CODEGEN"."TRAININGPLAN" ("PLANID") 
  ;
 
REM CODEGEN usecasemaster_pk

  CREATE UNIQUE INDEX "CODEGEN"."usecasemaster_pk" ON "CODEGEN"."USECASEMASTER" ("USECASE_NAME", "PROJECT_ID") 
  ;
 
REM CODEGEN USERENROLL_PK

  CREATE UNIQUE INDEX "CODEGEN"."USERENROLL_PK" ON "CODEGEN"."USERENROLL" ("ENROLLMENTID") 
  ;
 